include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - test/**
    - integration_test/**
    - build/**
    - .dart_tool/**

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - avoid_print: false
