name: marketplace_app
description: Une marketplace moderne et fluide

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.19.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Navigation
  cupertino_icons: ^1.0.2
  
  # HTTP & API
  http: ^1.2.2
  dio: ^5.9.0
  
  # State Management
  provider: ^6.1.2
  
  # Storage & Persistence
  shared_preferences: ^2.2.3
  
  # Authentication & Security
  crypto: ^3.0.2
  flutter_secure_storage: ^9.2.2
  flutter_dotenv: ^5.1.0
  
  # Images & Media
  cached_network_image: ^3.4.0
  
  # Connectivity
  connectivity_plus: ^6.1.5
  web_socket_channel: ^3.0.3
  
  # Dependency Injection
  get_it: ^7.6.0
  injectable: ^2.3.0
  
  # Animations & Effects
  shimmer: ^2.0.0
  
  # UI Enhancements
  flutter_rating_bar: ^4.0.1
  
  # Localization
  flutter_localizations:
    sdk: flutter
  intl: 0.20.2
  
  # Utilities & Helpers
  uuid: ^4.5.1
  
  # Additional utilities
  fl_chart: ^0.71.0
  device_info_plus: ^9.0.0
  package_info_plus: ^4.0.0
  path_provider: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  integration_test:
    sdk: flutter
  mockito: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/l10n/